<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program [
<!ATTLIST program name CDATA #REQUIRED>
<!ELEMENT program (cfgs,srcfile*)>
<!ELEMENT cfgs (cfg*)>
<!ATTLIST cfg
   id ID #REQUIRED
   main CDATA #IMPLIED
   name CDATA #IMPLIED>
<!ELEMENT cfg (bb+)>
<!ATTLIST bb id ID #REQUIRED>
<!ELEMENT bb (prec?,inst*,succ?)>
<!ELEMENT prec (link+)>
<!ELEMENT succ (link+)>
<!ATTLIST link
   type (taken|nottaken|call) #REQUIRED
   cfg IDREF #REQUIRED
   bb IDREF #REQUIRED
   cond CDATA #IMPLIED>
<!ELEMENT link EMPTY>
<!ATTLIST inst
   src IDREF #IMPLIED
   line CDATA #IMPLIED
   addr CDATA #REQUIRED
   type (ipoint|label|op|jump|branch|call|ret) #IMPLIED
   name CDATA #IMPLIED
   operands CDATA #IMPLIED
   cond CDATA #IMPLIED>
<!ELEMENT inst EMPTY>
<!ATTLIST srcfile
   id ID #REQUIRED
   name CDATA #IMPLIED>
<!ELEMENT srcfile (#PCDATA)>
]>

<program name="main">
   <cfgs>
      <cfg id="c6" name="gnc__passive__opcs__compute" main="true">
         <bb id="c6b1">
            <inst addr="0x40100000" src="s1" line="11"/>
            <inst addr="0x40100004"/>
            <inst addr="0x40100008" src="s1" line="12"/>
            <inst addr="0x4010000C" src="s1" line="14"/>
            <inst addr="0x40100010"/>
            <inst addr="0x40100014"/>
            <inst addr="0x40100018" src="s1" line="15"/>
            <inst addr="0x4010001C"/>
            <inst addr="0x40100020"/>
            <inst addr="0x40100024" src="s1" line="16"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b2"/>
            </succ>
         </bb>
         <bb id="c6b2">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b1"/>
               <link type="nottaken" cfg="c6" bb="c6b7"/>
            </prec>
            <inst addr="0x40100028"/>
            <inst addr="0x4010002C"/>
            <inst addr="0x40100030"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b3"/>
               <link type="taken" cfg="c6" bb="c6b4"/>
            </succ>
         </bb>
         <bb id="c6b3">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b2"/>
            </prec>
            <inst addr="0x40100034"/>
            <inst addr="0x40100038" src="s1" line="22"/>
            <inst addr="0x4010003C"/>
            <succ>
               <link type="call" cfg="c7" bb="c7b1"/>
               <link type="nottaken" cfg="c6" bb="c6b7"/>
            </succ>
         </bb>
         <bb id="c6b4">
            <prec>
               <link type="taken" cfg="c6" bb="c6b2"/>
            </prec>
            <inst addr="0x40100034"/>
            <inst addr="0x40100054" src="s1" line="29"/>
            <inst addr="0x40100058"/>
            <inst addr="0x4010005C"/>
            <inst addr="0x40100060" src="s1" line="30"/>
            <inst addr="0x40100064"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b6"/>
            </succ>
         </bb>
         <bb id="c6b6">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b4"/>
               <link type="nottaken" cfg="c6" bb="c6b11"/>
            </prec>
            <inst addr="0x40100068"/>
            <inst addr="0x4010006C"/>
            <inst addr="0x40100070"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b8"/>
               <link type="taken" cfg="c6" bb="c6b9"/>
            </succ>
         </bb>
         <bb id="c6b7">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b3"/>
            </prec>
            <inst addr="0x40100040" src="s1" line="16"/>
            <inst addr="0x40100044"/>
            <inst addr="0x40100048"/>
            <inst addr="0x4010004C" src="s1" line="28"/>
            <inst addr="0x40100050"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b2"/>
            </succ>
         </bb>
         <bb id="c6b8">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b6"/>
            </prec>
            <inst addr="0x40100074"/>
            <inst addr="0x40100078" src="s1" line="32"/>
            <inst addr="0x4010007C"/>
            <succ>
               <link type="call" cfg="c8" bb="c8b1"/>
               <link type="nottaken" cfg="c6" bb="c6b11"/>
            </succ>
         </bb>
         <bb id="c6b9">
            <prec>
               <link type="taken" cfg="c6" bb="c6b6"/>
            </prec>
            <inst addr="0x40100074"/>
            <inst addr="0x40100094" src="s1" line="35"/>
            <inst addr="0x40100098"/>
            <inst addr="0x4010009C"/>
            <inst addr="0x401000A0" src="s1" line="11"/>
            <inst addr="0x401000A4" src="s1" line="37"/>
            <inst addr="0x401000A8"/>
            <inst addr="0x401000AC"/>
            <inst addr="0x401000B0"/>
         </bb>
         <bb id="c6b11">
            <prec>
               <link type="nottaken" cfg="c6" bb="c6b8"/>
            </prec>
            <inst addr="0x40100080" src="s1" line="30"/>
            <inst addr="0x40100084"/>
            <inst addr="0x40100088"/>
            <inst addr="0x4010008C" src="s1" line="33"/>
            <inst addr="0x40100090"/>
            <succ>
               <link type="nottaken" cfg="c6" bb="c6b6"/>
            </succ>
         </bb>
      </cfg>
      <cfg id="c7" name="xgnc__aocs">
         <bb id="c7b1">
            <prec>
               <link type="call" cfg="c6" bb="c6b3"/>
            </prec>
            <inst addr="0x401001CC" src="s2" line="34"/>
            <inst addr="0x401001D0" src="s2" line="37"/>
            <inst addr="0x401001D4"/>
            <succ>
               <link type="nottaken" cfg="c7" bb="c7b2"/>
            </succ>
         </bb>
         <bb id="c7b2">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b1"/>
               <link type="nottaken" cfg="c7" bb="c7b16"/>
            </prec>
            <inst addr="0x401001D8"/>
            <inst addr="0x401001DC"/>
            <inst addr="0x401001E0"/>
            <succ>
               <link type="nottaken" cfg="c7" bb="c7b3"/>
               <link type="taken" cfg="c7" bb="c7b4"/>
            </succ>
         </bb>
         <bb id="c7b3">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b2"/>
            </prec>
            <inst addr="0x401001E4"/>
            <inst addr="0x401001E8" src="s2" line="39"/>
            <inst addr="0x401001EC"/>
            <inst addr="0x401001F0"/>
            <inst addr="0x401001F4"/>
            <inst addr="0x401001F8"/>
            <inst addr="0x401001FC"/>
            <inst addr="0x40100200"/>
            <inst addr="0x40100204"/>
            <inst addr="0x40100208"/>
            <succ>
               <link type="call" cfg="c10" bb="c10b1"/>
               <link type="nottaken" cfg="c7" bb="c7b6"/>
            </succ>
         </bb>
         <bb id="c7b4">
            <prec>
               <link type="taken" cfg="c7" bb="c7b2"/>
            </prec>
            <inst addr="0x401001E4"/>
            <inst addr="0x4010033C" src="s2" line="71"/>
            <inst addr="0x40100340"/>
            <inst addr="0x40100344"/>
         </bb>
         <bb id="c7b6">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b3"/>
            </prec>
            <inst addr="0x4010020C" src="s2" line="41"/>
            <inst addr="0x40100210"/>
            <inst addr="0x40100214"/>
            <inst addr="0x40100218"/>
            <inst addr="0x4010021C"/>
            <inst addr="0x40100220"/>
            <succ>
               <link type="call" cfg="c11" bb="c11b1"/>
               <link type="nottaken" cfg="c7" bb="c7b8"/>
            </succ>
         </bb>
         <bb id="c7b8">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b6"/>
            </prec>
            <inst addr="0x40100224" src="s2" line="45"/>
            <inst addr="0x40100228"/>
            <inst addr="0x4010022C"/>
            <inst addr="0x40100230"/>
            <inst addr="0x40100234"/>
            <inst addr="0x40100238"/>
            <inst addr="0x4010023C"/>
            <inst addr="0x40100240"/>
            <inst addr="0x40100244"/>
            <inst addr="0x40100248"/>
            <inst addr="0x4010024C"/>
            <inst addr="0x40100250"/>
            <inst addr="0x40100254"/>
            <succ>
               <link type="call" cfg="c12" bb="c12b1"/>
               <link type="nottaken" cfg="c7" bb="c7b10"/>
            </succ>
         </bb>
         <bb id="c7b10">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b8"/>
            </prec>
            <inst addr="0x40100258" src="s2" line="54"/>
            <inst addr="0x4010025C"/>
            <inst addr="0x40100260"/>
            <inst addr="0x40100264"/>
            <inst addr="0x40100268"/>
            <inst addr="0x4010026C"/>
            <succ>
               <link type="call" cfg="c13" bb="c13b1"/>
               <link type="nottaken" cfg="c7" bb="c7b12"/>
            </succ>
         </bb>
         <bb id="c7b12">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b10"/>
            </prec>
            <inst addr="0x40100270" src="s2" line="58"/>
            <inst addr="0x40100274"/>
            <inst addr="0x40100278"/>
            <inst addr="0x4010027C"/>
            <inst addr="0x40100280"/>
            <inst addr="0x40100284"/>
            <inst addr="0x40100288"/>
            <inst addr="0x4010028C"/>
            <inst addr="0x40100290"/>
            <inst addr="0x40100294"/>
            <inst addr="0x40100298"/>
            <succ>
               <link type="call" cfg="c14" bb="c14b1"/>
               <link type="nottaken" cfg="c7" bb="c7b14"/>
            </succ>
         </bb>
         <bb id="c7b14">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b12"/>
            </prec>
            <inst addr="0x4010029C" src="s2" line="62"/>
            <inst addr="0x401002A0"/>
            <inst addr="0x401002A4"/>
            <inst addr="0x401002A8"/>
            <inst addr="0x401002AC"/>
            <inst addr="0x401002B0"/>
            <inst addr="0x401002B4"/>
            <inst addr="0x401002B8"/>
            <inst addr="0x401002BC"/>
            <inst addr="0x401002C0"/>
            <inst addr="0x401002C4"/>
            <inst addr="0x401002C8"/>
            <inst addr="0x401002CC"/>
            <inst addr="0x401002D0"/>
            <inst addr="0x401002D4"/>
            <inst addr="0x401002D8"/>
            <inst addr="0x401002DC"/>
            <inst addr="0x401002E0"/>
            <inst addr="0x401002E4"/>
            <inst addr="0x401002E8"/>
            <inst addr="0x401002EC"/>
            <inst addr="0x401002F0"/>
            <inst addr="0x401002F4"/>
            <inst addr="0x401002F8"/>
            <inst addr="0x401002FC"/>
            <inst addr="0x40100300"/>
            <inst addr="0x40100304"/>
            <inst addr="0x40100308"/>
            <inst addr="0x4010030C"/>
            <inst addr="0x40100310"/>
            <inst addr="0x40100314"/>
            <inst addr="0x40100318"/>
            <inst addr="0x4010031C"/>
            <inst addr="0x40100320"/>
            <inst addr="0x40100324"/>
            <succ>
               <link type="call" cfg="c15" bb="c15b1"/>
               <link type="nottaken" cfg="c7" bb="c7b16"/>
            </succ>
         </bb>
         <bb id="c7b16">
            <prec>
               <link type="nottaken" cfg="c7" bb="c7b14"/>
            </prec>
            <inst addr="0x40100328" src="s2" line="37"/>
            <inst addr="0x4010032C"/>
            <inst addr="0x40100330"/>
            <inst addr="0x40100334" src="s2" line="70"/>
            <inst addr="0x40100338"/>
            <succ>
               <link type="nottaken" cfg="c7" bb="c7b2"/>
            </succ>
         </bb>
      </cfg>
      <cfg id="c10" name="xgnc__guidance__gnc_q4_0_q3_0_q2_0_q1_0">
         <bb id="c10b1">
            <prec>
               <link type="call" cfg="c7" bb="c7b3"/>
            </prec>
            <inst addr="0x40100C10" src="s3" line="9"/>
            <inst addr="0x40100C14"/>
            <inst addr="0x40100C18"/>
            <inst addr="0x40100C1C" src="s3" line="17"/>
            <inst addr="0x40100C20"/>
            <inst addr="0x40100C24"/>
            <inst addr="0x40100C28"/>
            <inst addr="0x40100C2C"/>
            <inst addr="0x40100C30" src="s3" line="18"/>
            <inst addr="0x40100C34"/>
            <inst addr="0x40100C38"/>
            <inst addr="0x40100C3C"/>
            <inst addr="0x40100C40"/>
            <inst addr="0x40100C44" src="s3" line="19"/>
            <inst addr="0x40100C48"/>
            <inst addr="0x40100C4C"/>
            <inst addr="0x40100C50"/>
            <inst addr="0x40100C54"/>
            <inst addr="0x40100C58" src="s3" line="20"/>
            <inst addr="0x40100C5C"/>
            <inst addr="0x40100C60"/>
            <inst addr="0x40100C64"/>
            <inst addr="0x40100C68"/>
            <inst addr="0x40100C6C" src="s3" line="22"/>
            <inst addr="0x40100C70"/>
            <inst addr="0x40100C74"/>
            <inst addr="0x40100C78"/>
            <inst addr="0x40100C7C" src="s3" line="23"/>
            <inst addr="0x40100C80"/>
            <inst addr="0x40100C84"/>
            <inst addr="0x40100C88"/>
            <inst addr="0x40100C8C" src="s3" line="24"/>
            <inst addr="0x40100C90"/>
            <inst addr="0x40100C94"/>
            <inst addr="0x40100C98"/>
            <inst addr="0x40100C9C" src="s3" line="25"/>
            <inst addr="0x40100CA0"/>
            <inst addr="0x40100CA4"/>
            <inst addr="0x40100CA8"/>
            <inst addr="0x40100CAC" src="s3" line="26"/>
            <inst addr="0x40100CB0"/>
            <inst addr="0x40100CB4"/>
            <inst addr="0x40100CB8"/>
            <inst addr="0x40100CBC"/>
            <inst addr="0x40100CC0"/>
            <inst addr="0x40100CC4"/>
            <inst addr="0x40100CC8"/>
            <inst addr="0x40100CCC"/>
            <inst addr="0x40100CD0"/>
            <inst addr="0x40100CD4"/>
            <inst addr="0x40100CD8"/>
            <inst addr="0x40100CDC" src="s3" line="27"/>
            <inst addr="0x40100CE0"/>
            <inst addr="0x40100CE4"/>
         </bb>
      </cfg>
      <cfg id="c11" name="xgnc__guidance__gnc_attitude_calculation_start">
         <bb id="c11b1">
            <prec>
               <link type="call" cfg="c7" bb="c7b6"/>
            </prec>
            <inst addr="0x40100CE8" src="s3" line="78"/>
            <inst addr="0x40100CEC"/>
            <inst addr="0x40100CF0"/>
            <inst addr="0x40100CF4" src="s3" line="80"/>
            <inst addr="0x40100CF8"/>
            <inst addr="0x40100CFC"/>
            <inst addr="0x40100D00"/>
            <inst addr="0x40100D04" src="s3" line="88"/>
            <inst addr="0x40100D08"/>
            <inst addr="0x40100D0C"/>
            <inst addr="0x40100D10"/>
            <inst addr="0x40100D14"/>
            <inst addr="0x40100D18"/>
            <inst addr="0x40100D1C" src="s3" line="89"/>
            <inst addr="0x40100D20"/>
            <inst addr="0x40100D24"/>
            <inst addr="0x40100D28"/>
            <inst addr="0x40100D2C"/>
            <inst addr="0x40100D30"/>
            <inst addr="0x40100D34" src="s3" line="90"/>
            <inst addr="0x40100D38"/>
            <inst addr="0x40100D3C"/>
            <inst addr="0x40100D40"/>
            <inst addr="0x40100D44"/>
            <inst addr="0x40100D48"/>
            <inst addr="0x40100D4C" src="s3" line="91"/>
            <inst addr="0x40100D50"/>
            <inst addr="0x40100D54"/>
            <inst addr="0x40100D58"/>
            <inst addr="0x40100D5C"/>
            <inst addr="0x40100D60"/>
            <inst addr="0x40100D64" src="s3" line="92"/>
            <inst addr="0x40100D68"/>
            <inst addr="0x40100D6C"/>
            <inst addr="0x40100D70"/>
            <inst addr="0x40100D74"/>
            <inst addr="0x40100D78"/>
            <inst addr="0x40100D7C" src="s3" line="93"/>
            <inst addr="0x40100D80"/>
            <inst addr="0x40100D84"/>
            <inst addr="0x40100D88"/>
            <inst addr="0x40100D8C" src="s3" line="94"/>
            <inst addr="0x40100D90"/>
            <inst addr="0x40100D94"/>
            <inst addr="0x40100D98"/>
            <inst addr="0x40100D9C" src="s3" line="95"/>
            <inst addr="0x40100DA0"/>
            <inst addr="0x40100DA4"/>
            <inst addr="0x40100DA8"/>
            <inst addr="0x40100DAC"/>
            <inst addr="0x40100DB0"/>
            <inst addr="0x40100DB4" src="s3" line="96"/>
            <inst addr="0x40100DB8"/>
            <inst addr="0x40100DBC"/>
            <inst addr="0x40100DC0"/>
            <inst addr="0x40100DC4"/>
            <inst addr="0x40100DC8"/>
            <inst addr="0x40100DCC"/>
            <inst addr="0x40100DD0"/>
            <inst addr="0x40100DD4" src="s3" line="97"/>
            <inst addr="0x40100DD8"/>
            <inst addr="0x40100DDC" src="s3" line="98"/>
            <inst addr="0x40100DE0"/>
            <inst addr="0x40100DE4"/>
            <succ>
               <link type="call" cfg="c16" bb="c16b1"/>
               <link type="nottaken" cfg="c11" bb="c11b3"/>
            </succ>
         </bb>
         <bb id="c11b3">
            <prec>
               <link type="nottaken" cfg="c11" bb="c11b1"/>
            </prec>
            <inst addr="0x40100DE8" src="s3" line="99"/>
            <inst addr="0x40100DEC"/>
            <inst addr="0x40100DF0"/>
            <succ>
               <link type="call" cfg="c17" bb="c17b1"/>
               <link type="nottaken" cfg="c11" bb="c11b5"/>
            </succ>
         </bb>
         <bb id="c11b5">
            <prec>
               <link type="nottaken" cfg="c11" bb="c11b3"/>
            </prec>
            <inst addr="0x40100DF4" src="s3" line="100"/>
            <inst addr="0x40100DF8"/>
            <inst addr="0x40100DFC"/>
         </bb>
      </cfg>
      <cfg id="c16" name="xgnc__guidance__gnc_attitude_calculation_disable">
         <bb id="c16b1">
            <prec>
               <link type="call" cfg="c11" bb="c11b1"/>
            </prec>
            <inst addr="0x40100E00" src="s3" line="56"/>
            <inst addr="0x40100E04"/>
            <inst addr="0x40100E08" src="s3" line="57"/>
            <inst addr="0x40100E0C"/>
            <inst addr="0x40100E10"/>
            <inst addr="0x40100E14"/>
            <inst addr="0x40100E18" src="s3" line="65"/>
            <inst addr="0x40100E1C"/>
            <inst addr="0x40100E20"/>
            <inst addr="0x40100E24"/>
            <inst addr="0x40100E28"/>
            <inst addr="0x40100E2C"/>
            <inst addr="0x40100E30" src="s3" line="66"/>
            <inst addr="0x40100E34"/>
            <inst addr="0x40100E38"/>
            <inst addr="0x40100E3C"/>
            <inst addr="0x40100E40"/>
            <inst addr="0x40100E44"/>
            <inst addr="0x40100E48" src="s3" line="67"/>
            <inst addr="0x40100E4C"/>
            <inst addr="0x40100E50"/>
            <inst addr="0x40100E54"/>
            <inst addr="0x40100E58"/>
            <inst addr="0x40100E5C"/>
            <inst addr="0x40100E60" src="s3" line="68"/>
            <inst addr="0x40100E64"/>
            <inst addr="0x40100E68"/>
            <inst addr="0x40100E6C"/>
            <inst addr="0x40100E70"/>
            <inst addr="0x40100E74"/>
            <inst addr="0x40100E78" src="s3" line="69"/>
            <inst addr="0x40100E7C"/>
            <inst addr="0x40100E80"/>
            <inst addr="0x40100E84"/>
            <inst addr="0x40100E88"/>
            <inst addr="0x40100E8C"/>
            <inst addr="0x40100E90" src="s3" line="70"/>
            <inst addr="0x40100E94"/>
            <inst addr="0x40100E98"/>
            <inst addr="0x40100E9C"/>
            <inst addr="0x40100EA0" src="s3" line="71"/>
            <inst addr="0x40100EA4"/>
            <inst addr="0x40100EA8"/>
            <inst addr="0x40100EAC"/>
            <inst addr="0x40100EB0" src="s3" line="72"/>
            <inst addr="0x40100EB4"/>
            <inst addr="0x40100EB8"/>
            <inst addr="0x40100EBC"/>
            <inst addr="0x40100EC0"/>
            <inst addr="0x40100EC4"/>
            <inst addr="0x40100EC8" src="s3" line="73"/>
            <inst addr="0x40100ECC"/>
            <inst addr="0x40100ED0"/>
            <inst addr="0x40100ED4"/>
            <inst addr="0x40100ED8"/>
            <inst addr="0x40100EDC"/>
            <inst addr="0x40100EE0"/>
            <inst addr="0x40100EE4"/>
            <inst addr="0x40100EE8" src="s3" line="74"/>
            <inst addr="0x40100EEC"/>
            <inst addr="0x40100EF0" src="s3" line="75"/>
            <inst addr="0x40100EF4"/>
            <inst addr="0x40100EF8"/>
            <inst addr="0x40100EFC" src="s3" line="76"/>
            <inst addr="0x40100F00"/>
            <inst addr="0x40100F04"/>
         </bb>
      </cfg>
      <cfg id="c17" name="xgnc__guidance__gnc_attitude_calculation_init">
         <bb id="c17b1">
            <prec>
               <link type="call" cfg="c11" bb="c11b3"/>
            </prec>
            <inst addr="0x40100F08" src="s3" line="29"/>
            <inst addr="0x40100F0C"/>
            <inst addr="0x40100F10" src="s3" line="30"/>
            <inst addr="0x40100F14"/>
            <inst addr="0x40100F18"/>
            <inst addr="0x40100F1C"/>
            <inst addr="0x40100F20" src="s3" line="38"/>
            <inst addr="0x40100F24"/>
            <inst addr="0x40100F28"/>
            <inst addr="0x40100F2C"/>
            <inst addr="0x40100F30"/>
            <inst addr="0x40100F34"/>
            <inst addr="0x40100F38" src="s3" line="39"/>
            <inst addr="0x40100F3C"/>
            <inst addr="0x40100F40"/>
            <inst addr="0x40100F44"/>
            <inst addr="0x40100F48"/>
            <inst addr="0x40100F4C"/>
            <inst addr="0x40100F50" src="s3" line="40"/>
            <inst addr="0x40100F54"/>
            <inst addr="0x40100F58"/>
            <inst addr="0x40100F5C"/>
            <inst addr="0x40100F60"/>
            <inst addr="0x40100F64"/>
            <inst addr="0x40100F68" src="s3" line="41"/>
            <inst addr="0x40100F6C"/>
            <inst addr="0x40100F70"/>
            <inst addr="0x40100F74"/>
            <inst addr="0x40100F78"/>
            <inst addr="0x40100F7C"/>
            <inst addr="0x40100F80" src="s3" line="42"/>
            <inst addr="0x40100F84"/>
            <inst addr="0x40100F88"/>
            <inst addr="0x40100F8C"/>
            <inst addr="0x40100F90"/>
            <inst addr="0x40100F94"/>
            <inst addr="0x40100F98" src="s3" line="43"/>
            <inst addr="0x40100F9C"/>
            <inst addr="0x40100FA0"/>
            <inst addr="0x40100FA4"/>
            <inst addr="0x40100FA8" src="s3" line="44"/>
            <inst addr="0x40100FAC"/>
            <inst addr="0x40100FB0"/>
            <inst addr="0x40100FB4"/>
            <inst addr="0x40100FB8" src="s3" line="45"/>
            <inst addr="0x40100FBC"/>
            <inst addr="0x40100FC0"/>
            <inst addr="0x40100FC4"/>
            <inst addr="0x40100FC8"/>
            <inst addr="0x40100FCC"/>
            <inst addr="0x40100FD0" src="s3" line="46"/>
            <inst addr="0x40100FD4"/>
            <inst addr="0x40100FD8"/>
            <inst addr="0x40100FDC"/>
            <inst addr="0x40100FE0"/>
            <inst addr="0x40100FE4"/>
            <inst addr="0x40100FE8"/>
            <inst addr="0x40100FEC"/>
            <inst addr="0x40100FF0" src="s3" line="47"/>
            <inst addr="0x40100FF4"/>
            <inst addr="0x40100FF8" src="s3" line="48"/>
            <inst addr="0x40100FFC"/>
            <inst addr="0x40101000"/>
            <inst addr="0x40101004"/>
            <inst addr="0x40101008"/>
            <inst addr="0x4010100C" src="s3" line="49"/>
            <inst addr="0x40101010"/>
            <inst addr="0x40101014"/>
            <inst addr="0x40101018"/>
            <inst addr="0x4010101C"/>
            <inst addr="0x40101020" src="s3" line="50"/>
            <inst addr="0x40101024"/>
            <inst addr="0x40101028"/>
            <inst addr="0x4010102C"/>
            <inst addr="0x40101030"/>
            <inst addr="0x40101034" src="s3" line="51"/>
            <inst addr="0x40101038"/>
            <inst addr="0x4010103C"/>
            <inst addr="0x40101040"/>
            <inst addr="0x40101044"/>
            <inst addr="0x40101048" src="s3" line="52"/>
            <inst addr="0x4010104C"/>
            <inst addr="0x40101050"/>
            <inst addr="0x40101054" src="s3" line="53"/>
            <inst addr="0x40101058"/>
            <inst addr="0x4010105C"/>
            <inst addr="0x40101060" src="s3" line="54"/>
            <inst addr="0x40101064"/>
            <inst addr="0x40101068"/>
         </bb>
      </cfg>
      <cfg id="c12" name="xgnc__guidance__gnc_attitude_calculation">
         <bb id="c12b1">
            <prec>
               <link type="call" cfg="c7" bb="c7b8"/>
            </prec>
            <inst addr="0x4010106C" src="s3" line="102"/>
            <inst addr="0x40101070"/>
            <inst addr="0x40101074"/>
            <inst addr="0x40101078"/>
            <inst addr="0x4010107C"/>
            <inst addr="0x40101080" src="s3" line="123"/>
            <inst addr="0x40101084"/>
            <inst addr="0x40101088"/>
            <inst addr="0x4010108C"/>
            <inst addr="0x40101090"/>
            <inst addr="0x40101094"/>
            <inst addr="0x40101098"/>
            <inst addr="0x4010109C"/>
            <inst addr="0x401010A0"/>
            <inst addr="0x401010A4"/>
            <inst addr="0x401010A8"/>
            <inst addr="0x401010AC"/>
            <inst addr="0x401010B0"/>
            <inst addr="0x401010B4"/>
            <inst addr="0x401010B8"/>
            <inst addr="0x401010BC"/>
            <inst addr="0x401010C0" src="s3" line="124"/>
            <inst addr="0x401010C4"/>
            <inst addr="0x401010C8"/>
            <inst addr="0x401010CC"/>
            <inst addr="0x401010D0" src="s3" line="125"/>
            <inst addr="0x401010D4"/>
            <inst addr="0x401010D8"/>
            <inst addr="0x401010DC"/>
            <inst addr="0x401010E0" src="s3" line="126"/>
            <inst addr="0x401010E4"/>
            <inst addr="0x401010E8"/>
            <inst addr="0x401010EC"/>
            <inst addr="0x401010F0"/>
            <inst addr="0x401010F4"/>
            <inst addr="0x401010F8"/>
            <inst addr="0x401010FC"/>
            <inst addr="0x40101100"/>
            <inst addr="0x40101104"/>
            <inst addr="0x40101108"/>
            <inst addr="0x4010110C"/>
            <inst addr="0x40101110"/>
            <inst addr="0x40101114"/>
            <inst addr="0x40101118"/>
            <inst addr="0x4010111C"/>
            <inst addr="0x40101120" src="s3" line="127"/>
            <inst addr="0x40101124"/>
            <inst addr="0x40101128"/>
            <inst addr="0x4010112C"/>
            <inst addr="0x40101130"/>
            <inst addr="0x40101134"/>
            <inst addr="0x40101138"/>
            <inst addr="0x4010113C"/>
            <inst addr="0x40101140"/>
            <inst addr="0x40101144"/>
            <inst addr="0x40101148"/>
            <inst addr="0x4010114C"/>
            <inst addr="0x40101150"/>
            <inst addr="0x40101154"/>
            <inst addr="0x40101158"/>
            <inst addr="0x4010115C"/>
            <inst addr="0x40101160" src="s3" line="128"/>
            <inst addr="0x40101164"/>
            <inst addr="0x40101168"/>
            <inst addr="0x4010116C"/>
            <inst addr="0x40101170" src="s3" line="129"/>
            <inst addr="0x40101174"/>
            <inst addr="0x40101178"/>
            <inst addr="0x4010117C"/>
            <inst addr="0x40101180" src="s3" line="130"/>
            <inst addr="0x40101184"/>
            <inst addr="0x40101188"/>
            <inst addr="0x4010118C"/>
            <inst addr="0x40101190" src="s3" line="131"/>
            <inst addr="0x40101194"/>
            <inst addr="0x40101198"/>
            <inst addr="0x4010119C"/>
            <inst addr="0x401011A0" src="s3" line="132"/>
            <inst addr="0x401011A4"/>
            <inst addr="0x401011A8"/>
            <inst addr="0x401011AC"/>
            <inst addr="0x401011B0" src="s3" line="133"/>
            <inst addr="0x401011B4"/>
            <inst addr="0x401011B8"/>
            <inst addr="0x401011BC"/>
            <inst addr="0x401011C0" src="s3" line="136"/>
            <inst addr="0x401011C4"/>
            <inst addr="0x401011C8"/>
            <inst addr="0x401011CC" src="s3" line="138"/>
            <inst addr="0x401011D0" src="s3" line="145"/>
            <inst addr="0x401011D4"/>
            <inst addr="0x401011D8"/>
            <inst addr="0x401011DC"/>
            <inst addr="0x401011E0" src="s3" line="146"/>
            <inst addr="0x401011E4"/>
            <inst addr="0x401011E8"/>
            <inst addr="0x401011EC"/>
            <inst addr="0x401011F0" src="s3" line="147"/>
            <inst addr="0x401011F4"/>
            <inst addr="0x401011F8"/>
            <inst addr="0x401011FC"/>
            <inst addr="0x40101200" src="s3" line="148"/>
            <inst addr="0x40101204"/>
            <inst addr="0x40101208"/>
            <inst addr="0x4010120C"/>
            <inst addr="0x40101210" src="s3" line="149"/>
            <inst addr="0x40101214"/>
            <inst addr="0x40101218" src="s3" line="150"/>
            <inst addr="0x4010121C"/>
            <inst addr="0x40101220"/>
            <inst addr="0x40101224" src="s3" line="151"/>
            <inst addr="0x40101228"/>
            <inst addr="0x4010122C"/>